name: "marcat"
description: "Men Distance"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_bootstrap5: ^1.1.1+1
  get: ^4.7.2
  uuid: ^4.5.1
  phone_form_field: ^10.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  rename_app: ^1.6.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"
  android: true
  ios: true
  web: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/